name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
      # with:
        # Version of Redis to use
        #redis version: # optional, default is latest
        # Number of Redis databases
        #number of databases: # optional, default is 16
    - name: Unit tests
      run: dotnet test
