name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    #- name: Unit tests
    #  run: dotnet test
  
  publish:
    needs: [build]
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Package
      run:
        varsion=`date +%y%m%d-%H%m`
        echo $version
        dotnet pack src/Redis.Net -o ../../publish/ -c Release -p:PackageVersion=1.0.1-ci-$version
    - name: publish nuget
      run:
        echo $version
        dotnet nuget push **/*.nupkg -k ${{secrets.nuget_apikey}} -s nuget.org
